# Funding options for this project
# Remove or comment out any platforms you don't want to use

# GitHub Sponsors
# github: [pavlenkotm]

# Patreon
# patreon: reflekt

# Open Collective
# open_collective: reflekt

# Ko-fi
# ko_fi: reflekt

# Custom
# custom: ['https://reflekt.app/donate', 'https://buymeacoffee.com/reflekt']
